spring:
  cloud:
    stream:
      bindings:
        inboundAnswerSheetFinished:
          destination: answerSheetFinished
          content-type: application/json
          group: examresultGroup
        binder:
          zkNodes: 192.168.0.158
          brokers: 192.168.0.158